### PR TITLE
Cop has been split into two separate cops

### PR DESCRIPTION
**Pull request by davidenko87**
Changed the `Style/MethodMissing` to the new cops: `Style/MethodMissingSuper` and `Style/MissingRespondToMissing`

### CODE REVIEW

**Comment by arnoFleming** [comment]
👍

**Review by bermannoah — APPROVED** [review]

**Comment by linkyndy** [comment]
This change happened in `0.56.0`, while we're still at `0.52.1` with rubocop. Why was this change necessary? 🤔

**Comment by davidenko87** [comment]
You mean, frontend is still at `0.52.1` isn't it time to update to `0.60`?

**Comment by davidenko87** [comment]
> You mean, frontend is still at `0.52.1` isn't it time to update to `0.60`?

Ah wait, i see gem is using older version. I'll bump this and also bump the version

**Comment by julik** [comment]
@davidenko87 @bermannoah did you try hooking the changed gem into one of our libraries that use `wetransfer_style` before merging? At the very least this should be done before releasing `wetransfer_style` otherwise we will need to lock the `wetransfer_style` to a specific version.

**Comment by davidenko87** [comment]
I've tested it for Blackbird and all seems to work fine.

**Pull request merged**
