### PR TITLE
Upgrade rubocop to version 1.59.0

### PR DESCRIPTION
**Pull request by linkyndy**
Plus, support Ruby 3.3 by default and add all new cops that have decent defaults to the whitelist.

### CODE REVIEW

**Comment by pcriv** [comment]
Are we still using this gem? I think a lot of projects were moved to use standard-rb

**Comment by linkyndy** [comment]
I'm not aware of any migration away from this gem 🤔 Either way, before planning any migration we should unblock ourselves here first.

**Review by pcriv — APPROVED** [review]

**Comment by grdw** [comment]
> Are we still using this gem? I think a lot of projects were moved to use standard-rb

I think Spaceship just uses the standard rubocop one with some exceptions. But other projects are free to choose I guess, at this point.

**Review by iggydv — APPROVED** [review]

**Review by grdw — APPROVED** [review]

**Comment by linkyndy** [comment]
> > Are we still using this gem? I think a lot of projects were moved to use standard-rb
> 
> I think Spaceship just uses the standard rubocop one with some exceptions. But other projects are free to choose I guess, at this point.

I think it would be great deciding on a common tool for such thing. We created `wetransfer_style` for this exact purpose, but since there's so much bikeshedding something must've gone wrong along the way.

**Pull request merged**
